use strict;
use warnings;
use Module::Build;

my $builder = Module::Build->new(
    module_name         => 'Paginate',
    license             => 'artistic2',
    dist_author         => 'Jim Toth <jjtoth@vcu.edu>',
    dist_version_from   => 'lib/Paginate.pm',
    requires => {
        'Test::More' => 0,
        'version'    => 0,
    },
    add_to_cleanup      => [ 'Paginate-*' ],
);

$builder->create_build_script();
